### ISSUE TITLE
Installation Issue for 32 bit Windows OS

### ISSUE THREAD

**Issue by sambaranpal** [abhinath84/Sampadak#31]
Hello Abhishek,

Observed that there is Installation Issue for 32 bit Windows OS. As a open source should be better if installation is independent of Windows as well. Thanks in advance.

![image](https://user-images.githubusercontent.com/104295358/164965218-ee01f47d-d805-41f3-9f44-c1a48b2b9c69.png)

Thanks,
Sambaran

**Comment by abhinath84** [comment]
Added 32-bit exe (sampadak_x86.exe).

**Comment by sambaranpal** [comment]
HI AbhishekDa,

Checked, my PC having a missing DLL file,, will  fix and recheck and update
you.

**Comment by abhinath84** [comment]
Issue resolved, able to install Sampadak.
