### ISSUE TITLE
Observations Lead to Further Enhancements

### ISSUE THREAD

**Issue by sambaranpal** [abhinath84/Sampadak#32]
1. Theme based Font- Colour need to be revisited for user readability easiness.
2. Dedicated panel and feature required for customized Font color, font style and other formatting used to exist in other Editor
3. view - section should have options to switch views like different language like HTML, other markup languages etc.
4. Zoom in & Zoom out  feature is a must for editor could not find it now.
5. Comparator window view - as enhancement
6. Individual window should toggle upon double click like in Notepad++

![image](https://user-images.githubusercontent.com/104295358/166428113-d0e75689-2cd8-454f-b5c0-dfd5888e46c0.png)

**Comment by abhinath84** [comment]
1. Theme based Font- Colour need to be revisited for user readability easiness.
   > Sure, will check on this.

2. Dedicated panel and feature required for customized Font color, font style and other formatting used to exist in other Editor
    > There is a font change option available: **_Settings > Preferences > Font & Colors > Click button next to 'Editor Font'_**.
    > If the button is grayed out, then uncheck the **_Use the system fixed width font_** option which is paced above **_Editor Font_**.

3. view - section should have options to switch views like different language like HTML, other markup languages etc.
   > Need to check this requirement, you are talking about editing HTML, and other markup languages, or displaying them in the browser?

4. Zoom in & Zoom out feature is a must for editor could not find it now.
   > zoom-in: **_ctrl + scroll mouse wheel up_**.
   > zoom-out: **_ctrl + scroll mouse wheel down_**.

5. Comparator window view - as enhancement
   > Good option. thanks :)

6. Individual window should toggle upon double click like in Notepad++
   > Need to understand.
   > Are you referring to open documents in Sampadak by double-clicking on them? If yes, then you need to set Sampadak as the default editor for those document formats. Yes, that's possible, I'll guide you.

### NOTE:

1. Please check **_Settings > Preferences > Misc > Language > Bengali_** feature. It's fun :)
2. Please write something to search in text-field in toolbar & click '->' option next to text-field. It will open the browser tab on the editor with google search results on it :)
  > Yes, Sampadak has a browser option inside it :)

**Comment by abhinath84** [comment]
![editor font](https://user-images.githubusercontent.com/13361448/166477843-edb84250-9d53-4b7f-8e7e-12ffa8236235.png)
![misc-lang](https://user-images.githubusercontent.com/13361448/166478107-e866ba7a-e59d-491c-bfb3-36fe4afdedc2.png)
![search-option](https://user-images.githubusercontent.com/13361448/166478842-37b27c70-c458-4a1e-b28a-d64c813ec9ea.png)

**Comment by sambaranpal** [comment]
Great, will check it out!

Thank you so much.
